---
- name: Запустить Django-приложение с помощью Docker
  hosts: app
  become: yes
  tasks:
    - name: Убедиться, что Docker установлен
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Запустить контейнер с Django-приложением
      docker_container:
        name: django_app
        image: timurbabs/django
        state: started
        ports:
          - "8000:8000"
